# Leser inn navn, adresse, poststed og postkode via input()
name = input('Hva er ditt navn? ')
address = input('Hva er din adresse? ')
postalCode = input('Hva er ditt postnummer og poststed? ')
print(name + 's adresse er:')
print()
print(name)
print(address)
print(postalCode)
